// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMESgbyL2C48uVwA3zN9NnXDbjJcOPAfI',
    appId: '1:745043765856:web:d289777d7c223c4a24f105',
    messagingSenderId: '745043765856',
    projectId: 'my-awesome-mobile-app-674b0',
    authDomain: 'my-awesome-mobile-app-674b0.firebaseapp.com',
    storageBucket: 'my-awesome-mobile-app-674b0.firebasestorage.app',
    measurementId: 'G-1YPLQ1ZQ49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDCmIAFq8s-EZyKtEVE7XhE7wC_qP_LF4',
    appId: '1:745043765856:android:d10414d19d06cb2f24f105',
    messagingSenderId: '745043765856',
    projectId: 'my-awesome-mobile-app-674b0',
    storageBucket: 'my-awesome-mobile-app-674b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJbDW0hvNz-UeTCphCDisjPVEabkerQn0',
    appId: '1:745043765856:ios:7d8e071b5e6941ed24f105',
    messagingSenderId: '745043765856',
    projectId: 'my-awesome-mobile-app-674b0',
    storageBucket: 'my-awesome-mobile-app-674b0.firebasestorage.app',
    iosBundleId: 'com.kamesh.myMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJbDW0hvNz-UeTCphCDisjPVEabkerQn0',
    appId: '1:745043765856:ios:7d8e071b5e6941ed24f105',
    messagingSenderId: '745043765856',
    projectId: 'my-awesome-mobile-app-674b0',
    storageBucket: 'my-awesome-mobile-app-674b0.firebasestorage.app',
    iosBundleId: 'com.kamesh.myMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMESgbyL2C48uVwA3zN9NnXDbjJcOPAfI',
    appId: '1:745043765856:web:4f34748e7c998f9824f105',
    messagingSenderId: '745043765856',
    projectId: 'my-awesome-mobile-app-674b0',
    authDomain: 'my-awesome-mobile-app-674b0.firebaseapp.com',
    storageBucket: 'my-awesome-mobile-app-674b0.firebasestorage.app',
    measurementId: 'G-DMX2TPDDNG',
  );
}
